export const NativeOperatorRegistryABI = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "getOperatorAdmin",
    inputs: [{ name: "_index", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOperatorFee",
    inputs: [{ name: "_index", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOperatorId",
    inputs: [{ name: "_name", type: "string", internalType: "string" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_owner", type: "address", internalType: "address" },
      { name: "_dvVaultAdmin", type: "address", internalType: "address" },
      { name: "_dvVaultOperatorFee", type: "uint16", internalType: "uint16" },
      {
        name: "_dvVaultManagers",
        type: "address[]",
        internalType: "address[]",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isManagerOfOperator",
    inputs: [
      { name: "_index", type: "bytes32", internalType: "bytes32" },
      { name: "_addr", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isOperatorRegistered",
    inputs: [{ name: "_name", type: "string", internalType: "string" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "registerOperator",
    inputs: [
      { name: "_name", type: "string", internalType: "string" },
      { name: "_admin", type: "address", internalType: "address" },
      { name: "_operatorFee", type: "uint16", internalType: "uint16" },
      { name: "_managers", type: "address[]", internalType: "address[]" },
    ],
    outputs: [{ name: "index", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOperatorManager",
    inputs: [
      { name: "_index", type: "bytes32", internalType: "bytes32" },
      { name: "_managers", type: "address[]", internalType: "address[]" },
      { name: "_isManager", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferAdminRole",
    inputs: [
      { name: "_index", type: "bytes32", internalType: "bytes32" },
      { name: "_newAdmin", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unregisterOperator",
    inputs: [{ name: "_index", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateOperatorFee",
    inputs: [
      { name: "_index", type: "bytes32", internalType: "bytes32" },
      { name: "_operatorFee", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      {
        name: "version",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OperatorCreated",
    inputs: [
      {
        name: "index",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      { name: "name", type: "string", indexed: false, internalType: "string" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OperatorManagerStatusChanged",
    inputs: [
      {
        name: "index",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "manager",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      { name: "isManager", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OperatorUnregistered",
    inputs: [
      {
        name: "index",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "FeeOutOfRange", inputs: [] },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  { type: "error", name: "NotOperatorAdmin", inputs: [] },
  { type: "error", name: "OperatorAlreadyExists", inputs: [] },
  { type: "error", name: "OperatorDoesNotExist", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
];
